### PR TITLE
SE2018春-MOOC-刘浥

### PR DESCRIPTION
**Pull request by blue-sky-sea**

### CODE REVIEW

**Comment by blue-sky-sea** [comment]
[SE2018春-MOOC-刘浥.pdf](https://github.com/SE2018-teachingAssistants/SE2018-teachingAssistants/files/2149782/SE2018.-MOOC-.pdf)

**Comment by skykingt** [comment]
[SE2018春MOOC-郦哲聪.docx](https://github.com/SE2018-teachingAssistants/SE2018-teachingAssistants/files/2149816/SE2018.MOOC-.docx)

**Comment by skykingt** [comment]
[SE2018春MOOC-陈铉文.docx](https://github.com/SE2018-teachingAssistants/SE2018-teachingAssistants/files/2149819/SE2018.MOOC-.docx)

**Comment by skykingt** [comment]
[SE2018春MOOC-陈铉文.pdf](https://github.com/SE2018-teachingAssistants/SE2018-teachingAssistants/files/2149853/SE2018.MOOC-.pdf)
[SE2018春MOOC-郦哲聪.pdf](https://github.com/SE2018-teachingAssistants/SE2018-teachingAssistants/files/2149854/SE2018.MOOC-.pdf)

**Comment by licecream** [comment]
[SE2018春MOOC-刘晓倩.pdf](https://github.com/SE2018-teachingAssistants/SE2018-teachingAssistants/files/2149938/SE2018.MOOC-.pdf)

**Comment by nikki-xyx** [comment]
[SE2018春-学堂在线-徐毓茜.pdf](https://github.com/SE2018-teachingAssistants/SE2018-teachingAssistants/files/2154989/SE2018.-.-.pdf)

**Pull request merged**
